# default preparations with grid sampling and random sampling.
voxel: 0.25

train:

  TargetTransform:
    _target_: myria3d.pctl.transforms.transforms.TargetTransform
    _args_:
      - ${dataset_description.classification_preprocessing_dict}
      - ${dataset_description.classification_dict}


  DropPointsByClass:
    _target_: myria3d.pctl.transforms.transforms.DropPointsByClass

  GridSampling:
    _target_: torch_geometric.transforms.GridSampling
    _args_:
      - ${datamodule.transforms.preparations.voxel}
  
  MinimumNumNodes:
    _target_: myria3d.pctl.transforms.transforms.MinimumNumNodes
    _args_:
      - 300

  MaximumNumNodes:
    _target_: myria3d.pctl.transforms.transforms.MaximumNumNodes
    _args_:
      - 40000

  Center:
    _target_: torch_geometric.transforms.Center
  
  TargetToOneHot:
    _target_: myria3d.pctl.transforms.transforms.TargetToOneHot
    _args_:
      - ${dataset_description.num_classes}

eval:

  TargetTransform:
    _target_: myria3d.pctl.transforms.transforms.TargetTransform
    _args_:
      - ${dataset_description.classification_preprocessing_dict}
      - ${dataset_description.classification_dict}

  DropPointsByClass:
    _target_: myria3d.pctl.transforms.transforms.DropPointsByClass

  CopyFullPos:
    _target_: myria3d.pctl.transforms.transforms.CopyFullPos

  CopyFullPreparedTargets:
    _target_: myria3d.pctl.transforms.transforms.CopyFullPreparedTargets

  GridSampling:
    _target_: torch_geometric.transforms.GridSampling
    _args_:
      - ${datamodule.transforms.preparations.voxel}

  MinimumNumNodes:
    _target_: myria3d.pctl.transforms.transforms.MinimumNumNodes
    _args_:
      - 300

  MaximumNumNodes:
    _target_: myria3d.pctl.transforms.transforms.MaximumNumNodes
    _args_:
      - 40000

  CopySampledPos:
    _target_: myria3d.pctl.transforms.transforms.CopySampledPos

  Center:
    _target_: torch_geometric.transforms.Center
    
  TargetToOneHot:
    _target_: myria3d.pctl.transforms.transforms.TargetToOneHot
    _args_:
      - ${dataset_description.num_classes}


predict:

  DropPointsByClass:
    _target_: myria3d.pctl.transforms.transforms.DropPointsByClass

  CopyFullPos:
    _target_: myria3d.pctl.transforms.transforms.CopyFullPos

  GridSampling:
    _target_: torch_geometric.transforms.GridSampling
    _args_:
      - ${datamodule.transforms.preparations.voxel}

  MinimumNumNodes:
    _target_: myria3d.pctl.transforms.transforms.MinimumNumNodes
    _args_:
      - 300

  MaximumNumNodes:
    _target_: myria3d.pctl.transforms.transforms.MaximumNumNodes
    _args_:
      - 40000

  CopySampledPos:
    _target_: myria3d.pctl.transforms.transforms.CopySampledPos

  Center:
    _target_: torch_geometric.transforms.Center