# lvl1 of my semantic label coarseness
# lvl 1 : only 3 labels


_conc_convert_: all  # For omegaconf struct to be converted to python dictionnaries
# classification_preprocessing_dict = {source_class_code_int: target_class_code_int},
# 3: medium vegetation -> vegetation
# 4: high vegetation -> vegetation
# 0: no processing --> unclassified
# 66: synthetic points --> noise (synthetic points are useful for specific modelling task on already classified data).
# We set them to noise so that they are ignored during training.
# Codes that should not have been in the data: 100, 101.
classification_preprocessing_dict: {0: 0, 1: 0, 2: 3, 3: 1, 4: 1, 5: 1, 6: 3, 7: 3, 8: 1, 9: 1, 10: 1, 11: 2, 12: 2, 13: 2, 14: 2, 15: 3, 16: 3, 17: 3, 18: 3}

# classification_dict = {code_int: name_str, ...} and MUST be sorted (increasing order).
classification_dict: {0: "Building", 1: "Soil", 2: "Vegetation", 3: "Void",}

# Input and output dims of neural net are dataset dependant:
class_weights: [1.0,1.0,1.0,1.0,]
d_in: 5
num_classes: 4 # 3 semantic classes + 1 void class
